version: '3.9'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/album
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=album
    ports:
      - 5432:5432
